// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: MenuScreen

#ifndef _MENUSCREEN_UI_H
#define _MENUSCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MenuScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_menu_icon_xiaozhi_ai_png);    // assets/images/menu/icon_xiaozhi_ai.png
LV_IMG_DECLARE(ui_img_images_menu_icon_weather_clock_png);    // assets/images/menu/icon_weather_clock.png
LV_IMG_DECLARE(ui_img_images_menu_icon_music_png);    // assets/images/menu/icon_music.png
LV_IMG_DECLARE(ui_img_images_menu_icon_muyu_png);    // assets/images/menu/icon_muyu.png
LV_IMG_DECLARE(ui_img_images_menu_icon_fm_png);    // assets/images/menu/icon_fm.png
LV_IMG_DECLARE(ui_img_images_menu_icon_pc_monitor_png);    // assets/images/menu/icon_pc_monitor.png

// FONTS
LV_FONT_DECLARE(ui_font_simhei16);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
