// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: musicplay

#ifndef _MUSICPLAY_UI_H
#define _MUSICPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MusicPlayScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_musicplay_icon_album_music_png);    // assets/images/musicplay/icon_album_music.png
LV_IMG_DECLARE(ui_img_images_musicplay_icon_volume_png);    // assets/images/musicplay/icon_volume.png
LV_IMG_DECLARE(ui_img_images_musicplay_icon_prev_png);    // assets/images/musicplay/icon_prev.png
LV_IMG_DECLARE(ui_img_images_musicplay_icon_play_png);    // assets/images/musicplay/icon_play.png
LV_IMG_DECLARE(ui_img_images_musicplay_icon_pause_png);    // assets/images/musicplay/icon_pause.png
LV_IMG_DECLARE(ui_img_images_musicplay_icon_next_png);    // assets/images/musicplay/icon_next.png

// FONTS
LV_FONT_DECLARE(musicplay_font_simhei16);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
