// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: musicplay

#ifndef UI_MUSICPLAYSCREEN_H
#define UI_MUSICPLAYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MusicPlayScreen
extern void ui_MusicPlayScreen_screen_init(void);
extern void ui_MusicPlayScreen_screen_destroy(void);
extern lv_obj_t * ui_MusicPlayScreen;
extern lv_obj_t * ui_bg_main;
extern lv_obj_t * ui_header_bar;
extern lv_obj_t * ui_labeldateweek;
extern lv_obj_t * ui_labeltitle;
extern lv_obj_t * ui_battery_group;
extern lv_obj_t * ui_batterybody;
extern lv_obj_t * ui_batteryhead;
extern lv_obj_t * ui_bar_battery_level;
extern lv_obj_t * ui_albumgroup;
extern lv_obj_t * ui_iconmusicnote2;
extern lv_obj_t * ui_albumdot01;
extern lv_obj_t * ui_albumdot02;
extern lv_obj_t * ui_albumdot03;
extern lv_obj_t * ui_albumdot04;
extern lv_obj_t * ui_album_dot_05;
extern lv_obj_t * ui_infogroup;
extern lv_obj_t * ui_labelsongname;
extern lv_obj_t * ui_labelsource;
extern lv_obj_t * ui_volumegroup;
extern lv_obj_t * ui_volumebar01;
extern lv_obj_t * ui_volumebar02;
extern lv_obj_t * ui_volume_bar_03;
extern lv_obj_t * ui_volume_bar_04;
extern lv_obj_t * ui_volumebar05;
extern lv_obj_t * ui_volumebar06;
extern lv_obj_t * ui_volumebar07;
extern lv_obj_t * ui_volumebar08;
extern lv_obj_t * ui_volumebar09;
extern lv_obj_t * ui_iconvolume;
extern lv_obj_t * ui_progressgroup;
extern lv_obj_t * ui_labeltimecurrent;
extern lv_obj_t * ui_barprogress;
extern lv_obj_t * ui_progress_knob;
extern lv_obj_t * ui_labeltimetotal;
extern lv_obj_t * ui_control_group;
extern lv_obj_t * ui_btnprev;
extern lv_obj_t * ui_iconprev;
extern lv_obj_t * ui_btn_play_pause;
extern lv_obj_t * ui_iconplaypause;
extern lv_obj_t * ui_btn_next;
extern lv_obj_t * ui_iconnext;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

