// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: musicplay

#include "../ui.h"

lv_obj_t * ui_MusicPlayScreen = NULL;
lv_obj_t * ui_bg_main = NULL;
lv_obj_t * ui_header_bar = NULL;
lv_obj_t * ui_labeldateweek = NULL;
lv_obj_t * ui_labeltitle = NULL;
lv_obj_t * ui_battery_group = NULL;
lv_obj_t * ui_batterybody = NULL;
lv_obj_t * ui_batteryhead = NULL;
lv_obj_t * ui_bar_battery_level = NULL;
lv_obj_t * ui_albumgroup = NULL;
lv_obj_t * ui_iconmusicnote2 = NULL;
lv_obj_t * ui_albumdot01 = NULL;
lv_obj_t * ui_albumdot02 = NULL;
lv_obj_t * ui_albumdot03 = NULL;
lv_obj_t * ui_albumdot04 = NULL;
lv_obj_t * ui_album_dot_05 = NULL;
lv_obj_t * ui_infogroup = NULL;
lv_obj_t * ui_labelsongname = NULL;
lv_obj_t * ui_labelsource = NULL;
lv_obj_t * ui_volumegroup = NULL;
lv_obj_t * ui_volumebar01 = NULL;
lv_obj_t * ui_volumebar02 = NULL;
lv_obj_t * ui_volume_bar_03 = NULL;
lv_obj_t * ui_volume_bar_04 = NULL;
lv_obj_t * ui_volumebar05 = NULL;
lv_obj_t * ui_volumebar06 = NULL;
lv_obj_t * ui_volumebar07 = NULL;
lv_obj_t * ui_volumebar08 = NULL;
lv_obj_t * ui_volumebar09 = NULL;
lv_obj_t * ui_iconvolume = NULL;
lv_obj_t * ui_progressgroup = NULL;
lv_obj_t * ui_labeltimecurrent = NULL;
lv_obj_t * ui_barprogress = NULL;
lv_obj_t * ui_progress_knob = NULL;
lv_obj_t * ui_labeltimetotal = NULL;
lv_obj_t * ui_control_group = NULL;
lv_obj_t * ui_btnprev = NULL;
lv_obj_t * ui_iconprev = NULL;
lv_obj_t * ui_btn_play_pause = NULL;
lv_obj_t * ui_iconplaypause = NULL;
lv_obj_t * ui_btn_next = NULL;
lv_obj_t * ui_iconnext = NULL;
// event funtions

// build funtions

void ui_MusicPlayScreen_screen_init(void)
{
    ui_MusicPlayScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MusicPlayScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicPlayScreen, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicPlayScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MusicPlayScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MusicPlayScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MusicPlayScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MusicPlayScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg_main = lv_obj_create(ui_MusicPlayScreen);
    lv_obj_set_width(ui_bg_main, 320);
    lv_obj_set_height(ui_bg_main, 240);
    lv_obj_remove_flag(ui_bg_main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_bg_main, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_bg_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bg_main, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bg_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bg_main, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bg_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bg_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_bg_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_bg_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_bg_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_bg_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_bar = lv_obj_create(ui_MusicPlayScreen);
    lv_obj_set_width(ui_header_bar, 320);
    lv_obj_set_height(ui_header_bar, 44);
    lv_obj_remove_flag(ui_header_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_header_bar, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_header_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header_bar, lv_color_hex(0x001438), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_header_bar, lv_color_hex(0x074373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header_bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_header_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_header_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_header_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_header_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeldateweek = lv_label_create(ui_header_bar);
    lv_obj_set_width(ui_labeldateweek, 104);
    lv_obj_set_height(ui_labeldateweek, 18);
    lv_obj_set_x(ui_labeldateweek, 6);
    lv_obj_set_y(ui_labeldateweek, 11);
    lv_label_set_long_mode(ui_labeldateweek, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_labeldateweek, "07/02 星期四");
    lv_obj_remove_flag(ui_labeldateweek, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_labeldateweek, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_labeldateweek, lv_color_hex(0xB6DCF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeldateweek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labeldateweek, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeldateweek, &musicplay_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeltitle = lv_label_create(ui_header_bar);
    lv_obj_set_width(ui_labeltitle, 84);
    lv_obj_set_height(ui_labeltitle, 22);
    lv_obj_set_x(ui_labeltitle, 130);
    lv_obj_set_y(ui_labeltitle, 11);
    lv_label_set_long_mode(ui_labeltitle, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_labeltitle, "音乐播放");
    lv_obj_remove_flag(ui_labeltitle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_labeltitle, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_labeltitle, lv_color_hex(0xF6FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeltitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labeltitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltitle, &musicplay_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery_group = lv_obj_create(ui_header_bar);
    lv_obj_set_width(ui_battery_group, 27);
    lv_obj_set_height(ui_battery_group, 16);
    lv_obj_set_x(ui_battery_group, 282);
    lv_obj_set_y(ui_battery_group, 15);
    lv_obj_remove_flag(ui_battery_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_battery_group, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_battery_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery_group, lv_color_hex(0x001438), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_battery_group, lv_color_hex(0x001438), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_battery_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_battery_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_battery_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_battery_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_battery_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_battery_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batterybody = lv_obj_create(ui_battery_group);
    lv_obj_set_width(ui_batterybody, 21);
    lv_obj_set_height(ui_batterybody, 13);
    lv_obj_set_x(ui_batterybody, 0);
    lv_obj_set_y(ui_batterybody, 1);
    lv_obj_remove_flag(ui_batterybody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_batterybody, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_batterybody, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_batterybody, lv_color_hex(0x031F45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batterybody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_batterybody, lv_color_hex(0xA0DAF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_batterybody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_batterybody, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_batterybody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_batterybody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_batterybody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_batterybody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryhead = lv_obj_create(ui_battery_group);
    lv_obj_set_width(ui_batteryhead, 3);
    lv_obj_set_height(ui_batteryhead, 5);
    lv_obj_set_x(ui_batteryhead, 22);
    lv_obj_set_y(ui_batteryhead, 5);
    lv_obj_remove_flag(ui_batteryhead, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_batteryhead, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_batteryhead, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_batteryhead, lv_color_hex(0xA0DAF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batteryhead, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_batteryhead, lv_color_hex(0xA0DAF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_batteryhead, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_batteryhead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_batteryhead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_batteryhead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_batteryhead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_batteryhead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar_battery_level = lv_bar_create(ui_battery_group);
    lv_bar_set_value(ui_bar_battery_level, 75, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_bar_battery_level, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bar_battery_level, 12);
    lv_obj_set_height(ui_bar_battery_level, 7);
    lv_obj_set_x(ui_bar_battery_level, 3);
    lv_obj_set_y(ui_bar_battery_level, 4);
    lv_obj_remove_flag(ui_bar_battery_level, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_bar_battery_level, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_bar_battery_level, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bar_battery_level, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar_battery_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar_battery_level, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar_battery_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bar_battery_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_bar_battery_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_bar_battery_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_bar_battery_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_bar_battery_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_bar_battery_level, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bar_battery_level, lv_color_hex(0x1DD3E8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar_battery_level, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar_battery_level, lv_color_hex(0x1DD3E8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar_battery_level, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bar_battery_level, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_bar_battery_level, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_bar_battery_level,
                                                                                                        lv_obj_get_style_pad_right(ui_bar_battery_level, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_albumgroup = lv_obj_create(ui_MusicPlayScreen);
    lv_obj_set_width(ui_albumgroup, 90);
    lv_obj_set_height(ui_albumgroup, 90);
    lv_obj_set_x(ui_albumgroup, 36);
    lv_obj_set_y(ui_albumgroup, 67);
    lv_obj_remove_flag(ui_albumgroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_albumgroup, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_albumgroup, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_albumgroup, lv_color_hex(0x003676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumgroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_albumgroup, lv_color_hex(0x1AD6F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_albumgroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_albumgroup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_albumgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_albumgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_albumgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_albumgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconmusicnote2 = lv_image_create(ui_albumgroup);
    lv_image_set_src(ui_iconmusicnote2, &ui_img_images_musicplay_icon_album_music_png);
    lv_obj_set_width(ui_iconmusicnote2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconmusicnote2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconmusicnote2, -1);
    lv_obj_set_y(ui_iconmusicnote2, -6);
    lv_obj_set_align(ui_iconmusicnote2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconmusicnote2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconmusicnote2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_albumdot01 = lv_obj_create(ui_albumgroup);
    lv_obj_set_width(ui_albumdot01, 4);
    lv_obj_set_height(ui_albumdot01, 4);
    lv_obj_set_x(ui_albumdot01, 16);
    lv_obj_set_y(ui_albumdot01, 70);
    lv_obj_remove_flag(ui_albumdot01, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_albumdot01, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_albumdot01, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_albumdot01, lv_color_hex(0x004687), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumdot01, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_albumdot01, lv_color_hex(0x004687), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_albumdot01, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_albumdot01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_albumdot01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_albumdot01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_albumdot01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_albumdot01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumdot02 = lv_obj_create(ui_albumgroup);
    lv_obj_set_width(ui_albumdot02, 4);
    lv_obj_set_height(ui_albumdot02, 4);
    lv_obj_set_x(ui_albumdot02, 28);
    lv_obj_set_y(ui_albumdot02, 70);
    lv_obj_remove_flag(ui_albumdot02, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_albumdot02, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_albumdot02, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_albumdot02, lv_color_hex(0x004687), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumdot02, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_albumdot02, lv_color_hex(0x004687), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_albumdot02, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_albumdot02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_albumdot02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_albumdot02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_albumdot02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_albumdot02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumdot03 = lv_obj_create(ui_albumgroup);
    lv_obj_set_width(ui_albumdot03, 4);
    lv_obj_set_height(ui_albumdot03, 4);
    lv_obj_set_x(ui_albumdot03, 40);
    lv_obj_set_y(ui_albumdot03, 70);
    lv_obj_remove_flag(ui_albumdot03, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_albumdot03, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_albumdot03, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_albumdot03, lv_color_hex(0x004687), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumdot03, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_albumdot03, lv_color_hex(0x004687), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_albumdot03, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_albumdot03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_albumdot03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_albumdot03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_albumdot03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_albumdot03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumdot04 = lv_obj_create(ui_albumgroup);
    lv_obj_set_width(ui_albumdot04, 4);
    lv_obj_set_height(ui_albumdot04, 4);
    lv_obj_set_x(ui_albumdot04, 52);
    lv_obj_set_y(ui_albumdot04, 70);
    lv_obj_remove_flag(ui_albumdot04, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_albumdot04, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_albumdot04, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_albumdot04, lv_color_hex(0x004687), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumdot04, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_albumdot04, lv_color_hex(0x004687), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_albumdot04, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_albumdot04, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_albumdot04, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_albumdot04, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_albumdot04, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_albumdot04, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_album_dot_05 = lv_obj_create(ui_albumgroup);
    lv_obj_set_width(ui_album_dot_05, 4);
    lv_obj_set_height(ui_album_dot_05, 4);
    lv_obj_set_x(ui_album_dot_05, 64);
    lv_obj_set_y(ui_album_dot_05, 70);
    lv_obj_remove_flag(ui_album_dot_05, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_album_dot_05, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_album_dot_05, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_album_dot_05, lv_color_hex(0x004687), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_album_dot_05, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_album_dot_05, lv_color_hex(0x004687), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_album_dot_05, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_album_dot_05, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_album_dot_05, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_album_dot_05, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_album_dot_05, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_album_dot_05, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_infogroup = lv_obj_create(ui_MusicPlayScreen);
    lv_obj_set_width(ui_infogroup, 160);
    lv_obj_set_height(ui_infogroup, 80);
    lv_obj_set_x(ui_infogroup, 145);
    lv_obj_set_y(ui_infogroup, 74);
    lv_obj_remove_flag(ui_infogroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_infogroup, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_infogroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_infogroup, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_infogroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_infogroup, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_infogroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_infogroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_infogroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_infogroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_infogroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_infogroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelsongname = lv_label_create(ui_infogroup);
    lv_obj_set_width(ui_labelsongname, 155);
    lv_obj_set_height(ui_labelsongname, 28);
    lv_label_set_long_mode(ui_labelsongname, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_labelsongname, "山海之间-音乐播放.mp3");
    lv_obj_remove_flag(ui_labelsongname, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_labelsongname, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_labelsongname, lv_color_hex(0xFAFCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelsongname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelsongname, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelsongname, &musicplay_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelsource = lv_label_create(ui_infogroup);
    lv_obj_set_width(ui_labelsource, 80);
    lv_obj_set_height(ui_labelsource, 20);
    lv_obj_set_x(ui_labelsource, 0);
    lv_obj_set_y(ui_labelsource, 35);
    lv_label_set_long_mode(ui_labelsource, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_labelsource, "TF卡音乐");
    lv_obj_remove_flag(ui_labelsource, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_labelsource, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_labelsource, lv_color_hex(0x9DC6E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelsource, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelsource, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelsource, &musicplay_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumegroup = lv_obj_create(ui_infogroup);
    lv_obj_set_width(ui_volumegroup, 112);
    lv_obj_set_height(ui_volumegroup, 30);
    lv_obj_set_x(ui_volumegroup, 0);
    lv_obj_set_y(ui_volumegroup, 58);
    lv_obj_set_ext_click_area(ui_volumegroup, 8);
    lv_obj_remove_flag(ui_volumegroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_volumegroup, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_volumegroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volumegroup, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumegroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volumegroup, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volumegroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volumegroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_volumegroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_volumegroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_volumegroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_volumegroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumebar01 = lv_obj_create(ui_volumegroup);
    lv_obj_set_width(ui_volumebar01, 5);
    lv_obj_set_height(ui_volumebar01, 7);
    lv_obj_set_x(ui_volumebar01, 31);
    lv_obj_set_y(ui_volumebar01, 16);
    lv_obj_remove_flag(ui_volumebar01, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_volumebar01, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_volumebar01, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volumebar01, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumebar01, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volumebar01, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volumebar01, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volumebar01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_volumebar01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_volumebar01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_volumebar01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_volumebar01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumebar02 = lv_obj_create(ui_volumegroup);
    lv_obj_set_width(ui_volumebar02, 5);
    lv_obj_set_height(ui_volumebar02, 9);
    lv_obj_set_x(ui_volumebar02, 39);
    lv_obj_set_y(ui_volumebar02, 14);
    lv_obj_remove_flag(ui_volumebar02, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_volumebar02, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_volumebar02, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volumebar02, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumebar02, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volumebar02, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volumebar02, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volumebar02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_volumebar02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_volumebar02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_volumebar02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_volumebar02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volume_bar_03 = lv_obj_create(ui_volumegroup);
    lv_obj_set_width(ui_volume_bar_03, 5);
    lv_obj_set_height(ui_volume_bar_03, 11);
    lv_obj_set_x(ui_volume_bar_03, 47);
    lv_obj_set_y(ui_volume_bar_03, 12);
    lv_obj_remove_flag(ui_volume_bar_03, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_volume_bar_03, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_volume_bar_03, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volume_bar_03, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volume_bar_03, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volume_bar_03, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volume_bar_03, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volume_bar_03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_volume_bar_03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_volume_bar_03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_volume_bar_03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_volume_bar_03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volume_bar_04 = lv_obj_create(ui_volumegroup);
    lv_obj_set_width(ui_volume_bar_04, 5);
    lv_obj_set_height(ui_volume_bar_04, 13);
    lv_obj_set_x(ui_volume_bar_04, 55);
    lv_obj_set_y(ui_volume_bar_04, 10);
    lv_obj_remove_flag(ui_volume_bar_04, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_volume_bar_04, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_volume_bar_04, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volume_bar_04, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volume_bar_04, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volume_bar_04, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volume_bar_04, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volume_bar_04, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_volume_bar_04, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_volume_bar_04, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_volume_bar_04, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_volume_bar_04, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumebar05 = lv_obj_create(ui_volumegroup);
    lv_obj_set_width(ui_volumebar05, 5);
    lv_obj_set_height(ui_volumebar05, 15);
    lv_obj_set_x(ui_volumebar05, 63);
    lv_obj_set_y(ui_volumebar05, 8);
    lv_obj_remove_flag(ui_volumebar05, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_volumebar05, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_volumebar05, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volumebar05, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumebar05, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volumebar05, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volumebar05, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volumebar05, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_volumebar05, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_volumebar05, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_volumebar05, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_volumebar05, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumebar06 = lv_obj_create(ui_volumegroup);
    lv_obj_set_width(ui_volumebar06, 5);
    lv_obj_set_height(ui_volumebar06, 17);
    lv_obj_set_x(ui_volumebar06, 71);
    lv_obj_set_y(ui_volumebar06, 6);
    lv_obj_remove_flag(ui_volumebar06, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_volumebar06, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_volumebar06, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volumebar06, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumebar06, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volumebar06, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volumebar06, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volumebar06, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_volumebar06, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_volumebar06, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_volumebar06, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_volumebar06, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumebar07 = lv_obj_create(ui_volumegroup);
    lv_obj_set_width(ui_volumebar07, 5);
    lv_obj_set_height(ui_volumebar07, 17);
    lv_obj_set_x(ui_volumebar07, 79);
    lv_obj_set_y(ui_volumebar07, 6);
    lv_obj_remove_flag(ui_volumebar07, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_volumebar07, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_volumebar07, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volumebar07, lv_color_hex(0x234E7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumebar07, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volumebar07, lv_color_hex(0x234E7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volumebar07, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volumebar07, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_volumebar07, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_volumebar07, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_volumebar07, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_volumebar07, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumebar08 = lv_obj_create(ui_volumegroup);
    lv_obj_set_width(ui_volumebar08, 5);
    lv_obj_set_height(ui_volumebar08, 17);
    lv_obj_set_x(ui_volumebar08, 87);
    lv_obj_set_y(ui_volumebar08, 6);
    lv_obj_remove_flag(ui_volumebar08, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_volumebar08, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_volumebar08, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volumebar08, lv_color_hex(0x234E7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumebar08, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volumebar08, lv_color_hex(0x234E7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volumebar08, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volumebar08, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_volumebar08, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_volumebar08, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_volumebar08, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_volumebar08, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumebar09 = lv_obj_create(ui_volumegroup);
    lv_obj_set_width(ui_volumebar09, 5);
    lv_obj_set_height(ui_volumebar09, 17);
    lv_obj_set_x(ui_volumebar09, 95);
    lv_obj_set_y(ui_volumebar09, 6);
    lv_obj_remove_flag(ui_volumebar09, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_volumebar09, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_volumebar09, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_volumebar09, lv_color_hex(0x234E7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumebar09, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volumebar09, lv_color_hex(0x234E7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volumebar09, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volumebar09, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_volumebar09, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_volumebar09, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_volumebar09, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_volumebar09, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconvolume = lv_image_create(ui_volumegroup);
    lv_image_set_src(ui_iconvolume, &ui_img_images_musicplay_icon_volume_png);
    lv_obj_set_width(ui_iconvolume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconvolume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconvolume, 0);
    lv_obj_set_y(ui_iconvolume, 2);
    lv_obj_add_flag(ui_iconvolume, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconvolume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_progressgroup = lv_obj_create(ui_MusicPlayScreen);
    lv_obj_set_width(ui_progressgroup, 308);
    lv_obj_set_height(ui_progressgroup, 20);
    lv_obj_set_x(ui_progressgroup, 5);
    lv_obj_set_y(ui_progressgroup, 168);
    lv_obj_remove_flag(ui_progressgroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_progressgroup, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_progressgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_progressgroup, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_progressgroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_progressgroup, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_progressgroup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_progressgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_progressgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_progressgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_progressgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_progressgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeltimecurrent = lv_label_create(ui_progressgroup);
    lv_obj_set_width(ui_labeltimecurrent, 40);
    lv_obj_set_height(ui_labeltimecurrent, 18);
    lv_obj_set_x(ui_labeltimecurrent, 0);
    lv_obj_set_y(ui_labeltimecurrent, 1);
    lv_label_set_long_mode(ui_labeltimecurrent, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_labeltimecurrent, "00:35");
    lv_obj_remove_flag(ui_labeltimecurrent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_labeltimecurrent, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_labeltimecurrent, lv_color_hex(0xE6EFFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeltimecurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labeltimecurrent, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltimecurrent, &musicplay_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barprogress = lv_bar_create(ui_progressgroup);
    lv_bar_set_value(ui_barprogress, 26, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barprogress, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barprogress, 205);
    lv_obj_set_height(ui_barprogress, 5);
    lv_obj_set_x(ui_barprogress, 50);
    lv_obj_set_y(ui_barprogress, 8);
    lv_obj_remove_flag(ui_barprogress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_barprogress, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_barprogress, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barprogress, lv_color_hex(0x184470), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barprogress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barprogress, lv_color_hex(0x184470), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barprogress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_barprogress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_barprogress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_barprogress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_barprogress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_barprogress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barprogress, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barprogress, lv_color_hex(0x23DDF1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barprogress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barprogress, lv_color_hex(0x23DDF1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barprogress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_barprogress, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barprogress, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barprogress,
                                                                                                  lv_obj_get_style_pad_right(ui_barprogress, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_progress_knob = lv_obj_create(ui_progressgroup);
    lv_obj_set_width(ui_progress_knob, 13);
    lv_obj_set_height(ui_progress_knob, 13);
    lv_obj_set_x(ui_progress_knob, 88);
    lv_obj_set_y(ui_progress_knob, 4);
    lv_obj_remove_flag(ui_progress_knob, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_progress_knob, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_progress_knob, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_progress_knob, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_progress_knob, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_progress_knob, lv_color_hex(0x23DDF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_progress_knob, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_progress_knob, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_progress_knob, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_progress_knob, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_progress_knob, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_progress_knob, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeltimetotal = lv_label_create(ui_progressgroup);
    lv_obj_set_width(ui_labeltimetotal, 38);
    lv_obj_set_height(ui_labeltimetotal, 18);
    lv_obj_set_x(ui_labeltimetotal, 263);
    lv_obj_set_y(ui_labeltimetotal, 1);
    lv_label_set_long_mode(ui_labeltimetotal, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_labeltimetotal, "03:42");
    lv_obj_remove_flag(ui_labeltimetotal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_labeltimetotal, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_labeltimetotal, lv_color_hex(0xE6EFFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeltimetotal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labeltimetotal, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltimetotal, &musicplay_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_control_group = lv_obj_create(ui_MusicPlayScreen);
    lv_obj_set_width(ui_control_group, 248);
    lv_obj_set_height(ui_control_group, 47);
    lv_obj_set_x(ui_control_group, 36);
    lv_obj_set_y(ui_control_group, 187);
    lv_obj_remove_flag(ui_control_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_control_group, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_control_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_control_group, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_control_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_control_group, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_control_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_control_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_control_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_control_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_control_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_control_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnprev = lv_obj_create(ui_control_group);
    lv_obj_set_width(ui_btnprev, 52);
    lv_obj_set_height(ui_btnprev, 33);
    lv_obj_set_x(ui_btnprev, 18);
    lv_obj_set_y(ui_btnprev, 6);
    lv_obj_remove_flag(ui_btnprev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_btnprev, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_btnprev, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnprev, lv_color_hex(0x003674), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnprev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnprev, lv_color_hex(0x14C1EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnprev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnprev, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btnprev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btnprev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btnprev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btnprev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconprev = lv_image_create(ui_btnprev);
    lv_image_set_src(ui_iconprev, &ui_img_images_musicplay_icon_prev_png);
    lv_obj_set_width(ui_iconprev, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconprev, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_iconprev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconprev, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconprev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_play_pause = lv_obj_create(ui_control_group);
    lv_obj_set_width(ui_btn_play_pause, 52);
    lv_obj_set_height(ui_btn_play_pause, 46);
    lv_obj_set_x(ui_btn_play_pause, 98);
    lv_obj_set_y(ui_btn_play_pause, 0);
    lv_obj_remove_flag(ui_btn_play_pause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_btn_play_pause, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_btn_play_pause, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_play_pause, lv_color_hex(0x003674), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_play_pause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_play_pause, lv_color_hex(0xFFB522), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_play_pause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_play_pause, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btn_play_pause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btn_play_pause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btn_play_pause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btn_play_pause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconplaypause = lv_image_create(ui_btn_play_pause);
    lv_image_set_src(ui_iconplaypause, &ui_img_images_musicplay_icon_pause_png);
    lv_obj_set_width(ui_iconplaypause, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconplaypause, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_iconplaypause, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconplaypause, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconplaypause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_next = lv_obj_create(ui_control_group);
    lv_obj_set_width(ui_btn_next, 52);
    lv_obj_set_height(ui_btn_next, 33);
    lv_obj_set_x(ui_btn_next, 178);
    lv_obj_set_y(ui_btn_next, 6);
    lv_obj_remove_flag(ui_btn_next, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_btn_next, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_btn_next, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_next, lv_color_hex(0x003674), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_next, lv_color_hex(0x14C1EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn_next, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btn_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btn_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btn_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btn_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconnext = lv_image_create(ui_btn_next);
    lv_image_set_src(ui_iconnext, &ui_img_images_musicplay_icon_next_png);
    lv_obj_set_width(ui_iconnext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconnext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_iconnext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconnext, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconnext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_MusicPlayScreen_screen_destroy(void)
{
    if(ui_MusicPlayScreen) lv_obj_del(ui_MusicPlayScreen);

    // NULL screen variables
    ui_MusicPlayScreen = NULL;
    ui_bg_main = NULL;
    ui_header_bar = NULL;
    ui_labeldateweek = NULL;
    ui_labeltitle = NULL;
    ui_battery_group = NULL;
    ui_batterybody = NULL;
    ui_batteryhead = NULL;
    ui_bar_battery_level = NULL;
    ui_albumgroup = NULL;
    ui_iconmusicnote2 = NULL;
    ui_albumdot01 = NULL;
    ui_albumdot02 = NULL;
    ui_albumdot03 = NULL;
    ui_albumdot04 = NULL;
    ui_album_dot_05 = NULL;
    ui_infogroup = NULL;
    ui_labelsongname = NULL;
    ui_labelsource = NULL;
    ui_volumegroup = NULL;
    ui_volumebar01 = NULL;
    ui_volumebar02 = NULL;
    ui_volume_bar_03 = NULL;
    ui_volume_bar_04 = NULL;
    ui_volumebar05 = NULL;
    ui_volumebar06 = NULL;
    ui_volumebar07 = NULL;
    ui_volumebar08 = NULL;
    ui_volumebar09 = NULL;
    ui_iconvolume = NULL;
    ui_progressgroup = NULL;
    ui_labeltimecurrent = NULL;
    ui_barprogress = NULL;
    ui_progress_knob = NULL;
    ui_labeltimetotal = NULL;
    ui_control_group = NULL;
    ui_btnprev = NULL;
    ui_iconprev = NULL;
    ui_btn_play_pause = NULL;
    ui_iconplaypause = NULL;
    ui_btn_next = NULL;
    ui_iconnext = NULL;

}
