// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: MenuScreen

#ifndef UI_MENUSCREEN_H
#define UI_MENUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MenuScreen
extern void ui_MenuScreen_screen_init(void);
extern void ui_MenuScreen_screen_destroy(void);
extern lv_obj_t * ui_MenuScreen;
extern lv_obj_t * ui_tile_xiaozhi_ai;
extern lv_obj_t * ui_slot_icon_xiaozhi_ai;
extern lv_obj_t * ui_slot_title_xiaozhi_ai;
extern lv_obj_t * ui_tile_weather_clock;
extern lv_obj_t * ui_slot_icon_weather_clock;
extern lv_obj_t * ui_slot_title_weather_clock;
extern lv_obj_t * ui_tile_music;
extern lv_obj_t * ui_slot_icon_music;
extern lv_obj_t * ui_slot_title_music;
extern lv_obj_t * ui_tile_muyu;
extern lv_obj_t * ui_slot_icon_muyu;
extern lv_obj_t * ui_slot_title_muyu;
extern lv_obj_t * ui_tile_fm;
extern lv_obj_t * ui_slot_icon_fm;
extern lv_obj_t * ui_slottitlefm;
extern lv_obj_t * ui_tile_pc_monitor;
extern lv_obj_t * ui_slot_icon_pc_monitor;
extern lv_obj_t * ui_slot_title_pc_monitor;
extern lv_obj_t * ui_group_page_indicator;
extern lv_obj_t * ui_page_dot_1;
extern lv_obj_t * ui_page_dot_2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

