// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: MenuScreen

#include "../ui.h"

lv_obj_t * ui_MenuScreen = NULL;
lv_obj_t * ui_tile_xiaozhi_ai = NULL;
lv_obj_t * ui_slot_icon_xiaozhi_ai = NULL;
lv_obj_t * ui_slot_title_xiaozhi_ai = NULL;
lv_obj_t * ui_tile_weather_clock = NULL;
lv_obj_t * ui_slot_icon_weather_clock = NULL;
lv_obj_t * ui_slot_title_weather_clock = NULL;
lv_obj_t * ui_tile_music = NULL;
lv_obj_t * ui_slot_icon_music = NULL;
lv_obj_t * ui_slot_title_music = NULL;
lv_obj_t * ui_tile_muyu = NULL;
lv_obj_t * ui_slot_icon_muyu = NULL;
lv_obj_t * ui_slot_title_muyu = NULL;
lv_obj_t * ui_tile_fm = NULL;
lv_obj_t * ui_slot_icon_fm = NULL;
lv_obj_t * ui_slottitlefm = NULL;
lv_obj_t * ui_tile_pc_monitor = NULL;
lv_obj_t * ui_slot_icon_pc_monitor = NULL;
lv_obj_t * ui_slot_title_pc_monitor = NULL;
lv_obj_t * ui_group_page_indicator = NULL;
lv_obj_t * ui_page_dot_1 = NULL;
lv_obj_t * ui_page_dot_2 = NULL;
// event funtions

// build funtions

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuScreen, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tile_xiaozhi_ai = lv_obj_create(ui_MenuScreen);
    lv_obj_set_width(ui_tile_xiaozhi_ai, 86);
    lv_obj_set_height(ui_tile_xiaozhi_ai, 80);
    lv_obj_set_x(ui_tile_xiaozhi_ai, 18);
    lv_obj_set_y(ui_tile_xiaozhi_ai, 24);
    lv_obj_remove_flag(ui_tile_xiaozhi_ai, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_tile_xiaozhi_ai, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_tile_xiaozhi_ai, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tile_xiaozhi_ai, lv_color_hex(0x003476), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tile_xiaozhi_ai, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tile_xiaozhi_ai, lv_color_hex(0x0074CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tile_xiaozhi_ai, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tile_xiaozhi_ai, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tile_xiaozhi_ai, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tile_xiaozhi_ai, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tile_xiaozhi_ai, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tile_xiaozhi_ai, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_icon_xiaozhi_ai = lv_image_create(ui_tile_xiaozhi_ai);
    lv_image_set_src(ui_slot_icon_xiaozhi_ai, &ui_img_images_menu_icon_xiaozhi_ai_png);
    lv_obj_set_width(ui_slot_icon_xiaozhi_ai, 52);
    lv_obj_set_height(ui_slot_icon_xiaozhi_ai, 44);
    lv_obj_set_x(ui_slot_icon_xiaozhi_ai, 17);
    lv_obj_set_y(ui_slot_icon_xiaozhi_ai, 8);
    lv_obj_remove_flag(ui_slot_icon_xiaozhi_ai, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_slot_icon_xiaozhi_ai, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_scrollbar_mode(ui_slot_icon_xiaozhi_ai, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_slot_icon_xiaozhi_ai, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot_icon_xiaozhi_ai, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_title_xiaozhi_ai = lv_label_create(ui_tile_xiaozhi_ai);
    lv_obj_set_width(ui_slot_title_xiaozhi_ai, 70);
    lv_obj_set_height(ui_slot_title_xiaozhi_ai, 22);
    lv_obj_set_x(ui_slot_title_xiaozhi_ai, 8);
    lv_obj_set_y(ui_slot_title_xiaozhi_ai, 54);
    lv_label_set_long_mode(ui_slot_title_xiaozhi_ai, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_slot_title_xiaozhi_ai, "小智AI");
    lv_obj_remove_flag(ui_slot_title_xiaozhi_ai, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_slot_title_xiaozhi_ai, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_slot_title_xiaozhi_ai, lv_color_hex(0xF6FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot_title_xiaozhi_ai, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_slot_title_xiaozhi_ai, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot_title_xiaozhi_ai, &ui_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tile_weather_clock = lv_obj_create(ui_MenuScreen);
    lv_obj_set_width(ui_tile_weather_clock, 86);
    lv_obj_set_height(ui_tile_weather_clock, 80);
    lv_obj_set_x(ui_tile_weather_clock, 117);
    lv_obj_set_y(ui_tile_weather_clock, 24);
    lv_obj_remove_flag(ui_tile_weather_clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_tile_weather_clock, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_tile_weather_clock, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tile_weather_clock, lv_color_hex(0x003476), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tile_weather_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tile_weather_clock, lv_color_hex(0x00E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tile_weather_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tile_weather_clock, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tile_weather_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tile_weather_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tile_weather_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tile_weather_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_icon_weather_clock = lv_image_create(ui_tile_weather_clock);
    lv_image_set_src(ui_slot_icon_weather_clock, &ui_img_images_menu_icon_weather_clock_png);
    lv_obj_set_width(ui_slot_icon_weather_clock, 52);
    lv_obj_set_height(ui_slot_icon_weather_clock, 44);
    lv_obj_set_x(ui_slot_icon_weather_clock, 17);
    lv_obj_set_y(ui_slot_icon_weather_clock, 8);
    lv_obj_remove_flag(ui_slot_icon_weather_clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_slot_icon_weather_clock, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_scrollbar_mode(ui_slot_icon_weather_clock, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_slot_icon_weather_clock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot_icon_weather_clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_title_weather_clock = lv_label_create(ui_tile_weather_clock);
    lv_obj_set_width(ui_slot_title_weather_clock, 70);
    lv_obj_set_height(ui_slot_title_weather_clock, 22);
    lv_obj_set_x(ui_slot_title_weather_clock, 8);
    lv_obj_set_y(ui_slot_title_weather_clock, 54);
    lv_label_set_long_mode(ui_slot_title_weather_clock, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_slot_title_weather_clock, "天气时钟");
    lv_obj_remove_flag(ui_slot_title_weather_clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_slot_title_weather_clock, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_slot_title_weather_clock, lv_color_hex(0xF6FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot_title_weather_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_slot_title_weather_clock, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot_title_weather_clock, &ui_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tile_music = lv_obj_create(ui_MenuScreen);
    lv_obj_set_width(ui_tile_music, 86);
    lv_obj_set_height(ui_tile_music, 80);
    lv_obj_set_x(ui_tile_music, 216);
    lv_obj_set_y(ui_tile_music, 24);
    lv_obj_remove_flag(ui_tile_music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_tile_music, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_tile_music, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tile_music, lv_color_hex(0x003476), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tile_music, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tile_music, lv_color_hex(0x0074CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tile_music, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tile_music, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tile_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tile_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tile_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tile_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_icon_music = lv_image_create(ui_tile_music);
    lv_image_set_src(ui_slot_icon_music, &ui_img_images_menu_icon_music_png);
    lv_obj_set_width(ui_slot_icon_music, 52);
    lv_obj_set_height(ui_slot_icon_music, 44);
    lv_obj_set_x(ui_slot_icon_music, 17);
    lv_obj_set_y(ui_slot_icon_music, 8);
    lv_obj_remove_flag(ui_slot_icon_music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_slot_icon_music, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_scrollbar_mode(ui_slot_icon_music, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_slot_icon_music, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot_icon_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_title_music = lv_label_create(ui_tile_music);
    lv_obj_set_width(ui_slot_title_music, 70);
    lv_obj_set_height(ui_slot_title_music, 22);
    lv_obj_set_x(ui_slot_title_music, 8);
    lv_obj_set_y(ui_slot_title_music, 54);
    lv_label_set_long_mode(ui_slot_title_music, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_slot_title_music, "音乐播放");
    lv_obj_remove_flag(ui_slot_title_music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_slot_title_music, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_slot_title_music, lv_color_hex(0xF6FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot_title_music, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_slot_title_music, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot_title_music, &ui_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tile_muyu = lv_obj_create(ui_MenuScreen);
    lv_obj_set_width(ui_tile_muyu, 86);
    lv_obj_set_height(ui_tile_muyu, 80);
    lv_obj_set_x(ui_tile_muyu, 18);
    lv_obj_set_y(ui_tile_muyu, 120);
    lv_obj_remove_flag(ui_tile_muyu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_tile_muyu, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_tile_muyu, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tile_muyu, lv_color_hex(0x003476), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tile_muyu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tile_muyu, lv_color_hex(0x0074CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tile_muyu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tile_muyu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tile_muyu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tile_muyu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tile_muyu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tile_muyu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_icon_muyu = lv_image_create(ui_tile_muyu);
    lv_image_set_src(ui_slot_icon_muyu, &ui_img_images_menu_icon_muyu_png);
    lv_obj_set_width(ui_slot_icon_muyu, 52);
    lv_obj_set_height(ui_slot_icon_muyu, 44);
    lv_obj_set_x(ui_slot_icon_muyu, 17);
    lv_obj_set_y(ui_slot_icon_muyu, 8);
    lv_obj_remove_flag(ui_slot_icon_muyu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_slot_icon_muyu, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_scrollbar_mode(ui_slot_icon_muyu, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_slot_icon_muyu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot_icon_muyu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_title_muyu = lv_label_create(ui_tile_muyu);
    lv_obj_set_width(ui_slot_title_muyu, 70);
    lv_obj_set_height(ui_slot_title_muyu, 22);
    lv_obj_set_x(ui_slot_title_muyu, 8);
    lv_obj_set_y(ui_slot_title_muyu, 54);
    lv_label_set_long_mode(ui_slot_title_muyu, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_slot_title_muyu, "木鱼");
    lv_obj_remove_flag(ui_slot_title_muyu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_slot_title_muyu, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_slot_title_muyu, lv_color_hex(0xF6FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot_title_muyu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_slot_title_muyu, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot_title_muyu, &ui_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tile_fm = lv_obj_create(ui_MenuScreen);
    lv_obj_set_width(ui_tile_fm, 86);
    lv_obj_set_height(ui_tile_fm, 80);
    lv_obj_set_x(ui_tile_fm, 117);
    lv_obj_set_y(ui_tile_fm, 120);
    lv_obj_remove_flag(ui_tile_fm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_tile_fm, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_tile_fm, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tile_fm, lv_color_hex(0x003476), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tile_fm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tile_fm, lv_color_hex(0x0074CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tile_fm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tile_fm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tile_fm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tile_fm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tile_fm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tile_fm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_icon_fm = lv_image_create(ui_tile_fm);
    lv_image_set_src(ui_slot_icon_fm, &ui_img_images_menu_icon_fm_png);
    lv_obj_set_width(ui_slot_icon_fm, 52);
    lv_obj_set_height(ui_slot_icon_fm, 44);
    lv_obj_set_x(ui_slot_icon_fm, 17);
    lv_obj_set_y(ui_slot_icon_fm, 8);
    lv_obj_remove_flag(ui_slot_icon_fm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_slot_icon_fm, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_scrollbar_mode(ui_slot_icon_fm, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_slot_icon_fm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot_icon_fm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slottitlefm = lv_label_create(ui_tile_fm);
    lv_obj_set_width(ui_slottitlefm, 70);
    lv_obj_set_height(ui_slottitlefm, 22);
    lv_obj_set_x(ui_slottitlefm, 8);
    lv_obj_set_y(ui_slottitlefm, 54);
    lv_label_set_long_mode(ui_slottitlefm, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_slottitlefm, "FM收音");
    lv_obj_remove_flag(ui_slottitlefm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_slottitlefm, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_slottitlefm, lv_color_hex(0xF6FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slottitlefm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_slottitlefm, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slottitlefm, &ui_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tile_pc_monitor = lv_obj_create(ui_MenuScreen);
    lv_obj_set_width(ui_tile_pc_monitor, 86);
    lv_obj_set_height(ui_tile_pc_monitor, 80);
    lv_obj_set_x(ui_tile_pc_monitor, 216);
    lv_obj_set_y(ui_tile_pc_monitor, 120);
    lv_obj_remove_flag(ui_tile_pc_monitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_tile_pc_monitor, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_tile_pc_monitor, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tile_pc_monitor, lv_color_hex(0x003476), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tile_pc_monitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tile_pc_monitor, lv_color_hex(0x0074CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tile_pc_monitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tile_pc_monitor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tile_pc_monitor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tile_pc_monitor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tile_pc_monitor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tile_pc_monitor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_icon_pc_monitor = lv_image_create(ui_tile_pc_monitor);
    lv_image_set_src(ui_slot_icon_pc_monitor, &ui_img_images_menu_icon_pc_monitor_png);
    lv_obj_set_width(ui_slot_icon_pc_monitor, 52);
    lv_obj_set_height(ui_slot_icon_pc_monitor, 44);
    lv_obj_set_x(ui_slot_icon_pc_monitor, 17);
    lv_obj_set_y(ui_slot_icon_pc_monitor, 8);
    lv_obj_remove_flag(ui_slot_icon_pc_monitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_slot_icon_pc_monitor, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_scrollbar_mode(ui_slot_icon_pc_monitor, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_slot_icon_pc_monitor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slot_icon_pc_monitor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot_title_pc_monitor = lv_label_create(ui_tile_pc_monitor);
    lv_obj_set_width(ui_slot_title_pc_monitor, 70);
    lv_obj_set_height(ui_slot_title_pc_monitor, 22);
    lv_obj_set_x(ui_slot_title_pc_monitor, 8);
    lv_obj_set_y(ui_slot_title_pc_monitor, 54);
    lv_label_set_long_mode(ui_slot_title_pc_monitor, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_slot_title_pc_monitor, "电脑监控");
    lv_obj_remove_flag(ui_slot_title_pc_monitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_slot_title_pc_monitor, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_slot_title_pc_monitor, lv_color_hex(0xF6FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slot_title_pc_monitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_slot_title_pc_monitor, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slot_title_pc_monitor, &ui_font_simhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_group_page_indicator = lv_obj_create(ui_MenuScreen);
    lv_obj_set_width(ui_group_page_indicator, 30);
    lv_obj_set_height(ui_group_page_indicator, 8);
    lv_obj_set_x(ui_group_page_indicator, 145);
    lv_obj_set_y(ui_group_page_indicator, 221);
    lv_obj_remove_flag(ui_group_page_indicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_group_page_indicator, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_group_page_indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_group_page_indicator, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_group_page_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_group_page_indicator, lv_color_hex(0x001234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_group_page_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_group_page_indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_group_page_indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_group_page_indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_group_page_indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_group_page_indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_dot_1 = lv_obj_create(ui_group_page_indicator);
    lv_obj_set_width(ui_page_dot_1, 8);
    lv_obj_set_height(ui_page_dot_1, 8);
    lv_obj_remove_flag(ui_page_dot_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_page_dot_1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_page_dot_1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_dot_1, lv_color_hex(0x0089D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_dot_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_dot_1, lv_color_hex(0x0089D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page_dot_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_dot_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_page_dot_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_page_dot_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_page_dot_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_page_dot_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page_dot_2 = lv_obj_create(ui_group_page_indicator);
    lv_obj_set_width(ui_page_dot_2, 8);
    lv_obj_set_height(ui_page_dot_2, 8);
    lv_obj_set_x(ui_page_dot_2, 22);
    lv_obj_set_y(ui_page_dot_2, 0);
    lv_obj_remove_flag(ui_page_dot_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_page_dot_2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_page_dot_2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_page_dot_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_dot_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_page_dot_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_page_dot_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_page_dot_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_page_dot_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_page_dot_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_page_dot_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_page_dot_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MenuScreen_screen_destroy(void)
{
    if(ui_MenuScreen) lv_obj_del(ui_MenuScreen);

    // NULL screen variables
    ui_MenuScreen = NULL;
    ui_tile_xiaozhi_ai = NULL;
    ui_slot_icon_xiaozhi_ai = NULL;
    ui_slot_title_xiaozhi_ai = NULL;
    ui_tile_weather_clock = NULL;
    ui_slot_icon_weather_clock = NULL;
    ui_slot_title_weather_clock = NULL;
    ui_tile_music = NULL;
    ui_slot_icon_music = NULL;
    ui_slot_title_music = NULL;
    ui_tile_muyu = NULL;
    ui_slot_icon_muyu = NULL;
    ui_slot_title_muyu = NULL;
    ui_tile_fm = NULL;
    ui_slot_icon_fm = NULL;
    ui_slottitlefm = NULL;
    ui_tile_pc_monitor = NULL;
    ui_slot_icon_pc_monitor = NULL;
    ui_slot_title_pc_monitor = NULL;
    ui_group_page_indicator = NULL;
    ui_page_dot_1 = NULL;
    ui_page_dot_2 = NULL;

}
